package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
	"repoctr/pkg/models"
)

const projectsFileName = "projects.yaml"

// NewInitCmd creates the init command.
func NewInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a projects.yaml template",
		Long:  "Creates a projects.yaml template file in the current directory.",
		RunE:  runInit,
	}

	return cmd
}

func runInit(cmd *cobra.Command, args []string) error {
	// Check if projects.yaml already exists
	if _, err := os.Stat(projectsFileName); err == nil {
		return fmt.Errorf("%s already exists. Use 'repo-ctr identify' to update it", projectsFileName)
	}

	// Create template config
	config := models.ProjectsConfig{
		Projects: []*models.Project{
			{
				Name:         "example-project",
				Path:         "path/to/project",
				Runtime:      models.Runtime{Type: models.RuntimeGo, Version: "1.21"},
				ManifestFile: "go.mod",
				SourcePaths:  []string{"."},
			},
		},
	}

	// Marshal to YAML
	data, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to create template: %w", err)
	}

	// Add header comment
	header := `# projects.yaml - Repository project configuration
# Generated by repo-ctr
# Run 'repo-ctr identify .' to auto-discover projects

`
	content := header + string(data)

	// Write file
	if err := os.WriteFile(projectsFileName, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", projectsFileName, err)
	}

	absPath, _ := filepath.Abs(projectsFileName)
	fmt.Printf("Created %s\n", absPath)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Run 'repo-ctr identify .' to auto-discover projects")
	fmt.Println("  2. Or manually edit projects.yaml")
	fmt.Println("  3. Run 'repo-ctr stats' to view statistics")

	return nil
}
